id: P4214711B
initial_creation_type: input
source_metadata:
  Title: 'The Caṇḍamahāroṣaṇa tantra: Chapters I-VIII'
  Editor: Christopher Starr George
  Publisher: University of Pennsylvania
  Place of Publication: Pennsylvania, USA
  Year: '1971'
  Caṇḍamahāroṣaṇa tantra:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:07:31.365984'
last_modified_at: '2022-03-08T17:07:31.365993'
